name: "PR Reusable Checks"

on:
  pull_request:

jobs:
  pr-branch-check-name:
    name: "Check PR for semantic branch name"
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-check-name.yml@main
  pr-title-check:
    name: "Check PR for semantic title"
    uses: mParticle/mparticle-workflows/.github/workflows/pr-title-check.yml@main
  pr-branch-target-gitflow:
    name: "Check PR for semantic target branch"
    uses: mParticle/mparticle-workflows/.github/workflows/pr-branch-target-gitflow.yml@main
